### ISSUE TITLE
Preapprove ans Subscription_orderId_issue_with_return_url

### ISSUE THREAD

**Issue by samfernando96** [pavinduLakshan/payhere-js-sdk#21]
This relevant to payhere-js-sdk NPM package only,

I used yours **NPM** package for a **preapprove** process . So I could to find there is a issue with **returnUrl**. Because after submit the form, redirect to returnurl with "**order_id**",but the value of order_id was a string like this "**[object object]**" . I tried different versions but result was same. I noticed there is no issue with "checkout" process. Issue happens with only "**Subscription**" and "**Preapprove**" packages.
So I could changed little code stuff  on **PreapprovalParams** class and I could to fix the issue with orderId.

And if it is a issue with package, kindly request the fix that and release quickly . thank u.

![Screenshot from 2022-09-21 17-17-43](https://user-images.githubusercontent.com/104185156/191686195-0a36ee9c-4bb9-462a-a862-00f71e13f4b0.png)

![Screenshot from 2022-09-21 17-16-55](https://user-images.githubusercontent.com/104185156/191686213-fdc82316-b6f8-411f-81c6-f19b61b6ead7.png)

**Comment by pavinduLakshan** [comment]
Hi @samfernando96 ,

Thanks for taking time to open an issue. I' ll have a look at it.

If you don't mind, can you provide me with a link to a reproducible code sample? Also, it would be great, if you can let me know what frontend framework you are using as well.

**Comment by samfernando96** [comment]
Thank you for considering my request. I was using the *React* library for
my front end development. Here I have attached a sample project with
changed *nodemoules*.

note: Here I have changed only compiled js files.
changed files:
1. SubscriptionParams.js
2. PreapprovalParams.js
 payhere-react-js-demo-app.zip
<https://drive.google.com/file/d/1g4dOsf_mDQYHtCmJm8tx0wZtz7nOmAuW/view?usp=drive_web>

**Comment by pavinduLakshan** [comment]
This should now be fixed in v1.0.2.
